// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// SIS_stochastic_async_cpp
Rcpp::List SIS_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIS_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIS_stochastic_hybrid_cpp
Rcpp::List SIS_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIS_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIS_stochastic_sync_cpp
Rcpp::List SIS_stochastic_sync_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIS_stochastic_sync_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIS_stochastic_sync_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_async_cpp
Rcpp::List SIR_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIR_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_hybrid_cpp
Rcpp::List SIR_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIR_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SIR_stochastic_sync_cpp
Rcpp::List SIR_stochastic_sync_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SIR_stochastic_sync_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SIR_stochastic_sync_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SLIR_stochastic_async_cpp
Rcpp::List SLIR_stochastic_async_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SLIR_stochastic_async_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SLIR_stochastic_async_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// SLIR_stochastic_hybrid_cpp
Rcpp::List SLIR_stochastic_hybrid_cpp(Rcpp::List args);
RcppExport SEXP _bobFunctions_SLIR_stochastic_hybrid_cpp(SEXP argsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type args(argsSEXP);
    rcpp_result_gen = Rcpp::wrap(SLIR_stochastic_hybrid_cpp(args));
    return rcpp_result_gen;
END_RCPP
}
// exit_cpp
void exit_cpp();
RcppExport SEXP _bobFunctions_exit_cpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    exit_cpp();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bobFunctions_SIS_stochastic_async_cpp", (DL_FUNC) &_bobFunctions_SIS_stochastic_async_cpp, 1},
    {"_bobFunctions_SIS_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctions_SIS_stochastic_hybrid_cpp, 1},
    {"_bobFunctions_SIS_stochastic_sync_cpp", (DL_FUNC) &_bobFunctions_SIS_stochastic_sync_cpp, 1},
    {"_bobFunctions_SIR_stochastic_async_cpp", (DL_FUNC) &_bobFunctions_SIR_stochastic_async_cpp, 1},
    {"_bobFunctions_SIR_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctions_SIR_stochastic_hybrid_cpp, 1},
    {"_bobFunctions_SIR_stochastic_sync_cpp", (DL_FUNC) &_bobFunctions_SIR_stochastic_sync_cpp, 1},
    {"_bobFunctions_SLIR_stochastic_async_cpp", (DL_FUNC) &_bobFunctions_SLIR_stochastic_async_cpp, 1},
    {"_bobFunctions_SLIR_stochastic_hybrid_cpp", (DL_FUNC) &_bobFunctions_SLIR_stochastic_hybrid_cpp, 1},
    {"_bobFunctions_exit_cpp", (DL_FUNC) &_bobFunctions_exit_cpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bobFunctions(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
