## This file was automatically generated by odin.
## Do not edit by hand as changes will be lost.
.R6_SIR_deterministic_odin <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "SIR_deterministic_odin",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("SIR_deterministic_odin_create", user, use_dde, PACKAGE = "bobFunctions")
      self$use_dde <- use_dde
      self$init <- .Call("SIR_deterministic_odin_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_SIR_deterministic_odin_set_user", self$ptr, user, PACKAGE = "bobFunctions")
      self$init <- .Call("SIR_deterministic_odin_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("SIR_deterministic_odin_variable_order", self$ptr, PACKAGE = "bobFunctions")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("SIR_deterministic_odin_deriv_r", self$ptr, t, y, PACKAGE = "bobFunctions")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "SIR_deterministic_odin_deriv_dde", self$ptr,
                          dllname="bobFunctions",
                          parms_are_real=FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "SIR_deterministic_odin_deriv_ds", self$ptr,
                            initfunc = "SIR_deterministic_odin_initmod_ds", dllname = "bobFunctions",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("SIR_deterministic_odin_contents", self$ptr, PACKAGE = "bobFunctions")
    }
  ))
SIR_deterministic_odin <- function(beta, r, mu, I_init, R_init, N, user = list(beta = beta, r = r, mu = mu, I_init = I_init, R_init = R_init, N = N), use_dde = FALSE) {
  .R6_SIR_deterministic_odin$new(user = user, use_dde = use_dde)
}
.R6_SIS_deterministic_odin <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "SIS_deterministic_odin",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("SIS_deterministic_odin_create", user, use_dde, PACKAGE = "bobFunctions")
      self$use_dde <- use_dde
      self$init <- .Call("SIS_deterministic_odin_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_SIS_deterministic_odin_set_user", self$ptr, user, PACKAGE = "bobFunctions")
      self$init <- .Call("SIS_deterministic_odin_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("SIS_deterministic_odin_variable_order", self$ptr, PACKAGE = "bobFunctions")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("SIS_deterministic_odin_deriv_r", self$ptr, t, y, PACKAGE = "bobFunctions")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "SIS_deterministic_odin_deriv_dde", self$ptr,
                          dllname="bobFunctions",
                          parms_are_real=FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "SIS_deterministic_odin_deriv_ds", self$ptr,
                            initfunc = "SIS_deterministic_odin_initmod_ds", dllname = "bobFunctions",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("SIS_deterministic_odin_contents", self$ptr, PACKAGE = "bobFunctions")
    }
  ))
SIS_deterministic_odin <- function(beta, r, I_init, N, user = list(beta = beta, r = r, I_init = I_init, N = N), use_dde = FALSE) {
  .R6_SIS_deterministic_odin$new(user = user, use_dde = use_dde)
}
.R6_SIS_deterministic_odin2 <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "SIS_deterministic_odin2",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("SIS_deterministic_odin2_create", user, use_dde, PACKAGE = "bobFunctions")
      self$use_dde <- use_dde
      self$init <- .Call("SIS_deterministic_odin2_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_SIS_deterministic_odin2_set_user", self$ptr, user, PACKAGE = "bobFunctions")
      self$init <- .Call("SIS_deterministic_odin2_initialise", self$ptr, NA_real_, PACKAGE = "bobFunctions")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("SIS_deterministic_odin2_variable_order", self$ptr, PACKAGE = "bobFunctions")
      odin_prepare(self, FALSE)
    },

    deriv = function(t, y) {
      .Call("SIS_deterministic_odin2_deriv_r", self$ptr, t, y, PACKAGE = "bobFunctions")
    },

    initial = function(t) {
      self$init
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$init
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "SIS_deterministic_odin2_deriv_dde", self$ptr,
                          dllname="bobFunctions",
                          parms_are_real=FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::ode(y, t, "SIS_deterministic_odin2_deriv_ds", self$ptr,
                            initfunc = "SIS_deterministic_odin2_initmod_ds", dllname = "bobFunctions",
                            ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("SIS_deterministic_odin2_contents", self$ptr, PACKAGE = "bobFunctions")
    }
  ))
SIS_deterministic_odin2 <- function(beta, r, I_init, N, user = list(beta = beta, r = r, I_init = I_init, N = N), use_dde = FALSE) {
  .R6_SIS_deterministic_odin2$new(user = user, use_dde = use_dde)
}
.R6_SLIR_deterministic_odin <- R6::R6Class(
  "odin_model",
  parent_env = environment(odin::odin),
  public = list(
    name = "SLIR_deterministic_odin",
    ptr = NULL,
    use_dde = NULL,
    ## Cache:
    init = NULL,
    variable_order = NULL,
    names = NULL,
    transform_variables = NULL,
    ## Methods:
    initialize = function(user = NULL, use_dde = FALSE) {
      self$ptr <- .Call("SLIR_deterministic_odin_create", user, use_dde, PACKAGE = "bobFunctions")
      self$use_dde <- use_dde
      if (use_dde) {
        loadNamespace("dde")
      }
      self$update_cache()
    },

    set_user = function(..., user = list(...)) {
      .Call("r_SLIR_deterministic_odin_set_user", self$ptr, user, PACKAGE = "bobFunctions")
      invisible(self$init)
    },

    update_cache = function() {
      self$variable_order <- .Call("SLIR_deterministic_odin_variable_order", self$ptr, PACKAGE = "bobFunctions")
      odin_prepare(self, FALSE)
    },

    initial = function(t) {
      .Call("SLIR_deterministic_odin_initialise", self$ptr, as.numeric(t), PACKAGE = "bobFunctions")
    },

    run = function(t, y = NULL, ..., use_names = TRUE) {
      if (is.null(y)) {
        y <- self$initial(t[[1L]])
      } else {
        .Call("SLIR_deterministic_odin_set_initial", self$ptr, t, y, PACKAGE = "bobFunctions")
      }
      if (self$use_dde) {
        ret <- dde::dopri(y, t, "SLIR_deterministic_odin_deriv_dde", self$ptr,
                          dllname="bobFunctions",
                          n_history=1000L, return_history=FALSE,
                          parms_are_real=FALSE, ynames = FALSE, ...)
      } else {
        ret <- deSolve::dede(y, t, "SLIR_deterministic_odin_deriv_ds", self$ptr,
                             initfunc = "SLIR_deterministic_odin_initmod_ds", dllname = "bobFunctions",
                             ...)
      }
      if (use_names) {
        colnames(ret) <- self$names
      } else {
        colnames(ret) <- NULL
      }
      ret
    },

    contents = function() {
      .Call("SLIR_deterministic_odin_contents", self$ptr, PACKAGE = "bobFunctions")
    }
  ))
SLIR_deterministic_odin <- function(beta, dur_lag, r, I_init, R_init, N, user = list(beta = beta, dur_lag = dur_lag, r = r, I_init = I_init, R_init = R_init, N = N), use_dde = FALSE) {
  .R6_SLIR_deterministic_odin$new(user = user, use_dde = use_dde)
}
